// ============================================================
// SERVICES — edit this file to change what the company offers.
// `slug` controls the URL: /services/{slug}
// `icon` is a lucide-react icon name (see lucide.dev).
// ============================================================
import { site } from '@/lib/site-config';

const city = site.address.city;

export const services = [
  {
    slug: 'emergency-plumbing',
    name: 'SERVICE_1_NAME_GOES_HERE',
    keyword: `SERVICE_1_PRIMARY_KEYWORD_GOES_HERE (e.g. emergency plumber ${city})`,
    icon: 'Siren',
    short: 'SERVICE_1_SHORT_DESCRIPTION_GOES_HERE',
    priceFrom: 149,
    duration: 'SERVICE_1_TYPICAL_DURATION_GOES_HERE',
    pricing: 'SERVICE_1_PRICING_EXPLANATION_GOES_HERE',
    hero: 'SERVICE_1_HERO_PARAGRAPH_GOES_HERE',
    includes: [
      'SERVICE_1_INCLUDE_1',
      'SERVICE_1_INCLUDE_2',
      'SERVICE_1_INCLUDE_3',
      'SERVICE_1_INCLUDE_4',
      'SERVICE_1_INCLUDE_5',
    ],
    signs: ['SERVICE_1_SIGN_1','SERVICE_1_SIGN_2','SERVICE_1_SIGN_3','SERVICE_1_SIGN_4','SERVICE_1_SIGN_5'],
    faq: [
      { q: 'SERVICE_1_FAQ_Q1', a: 'SERVICE_1_FAQ_A1' },
      { q: 'SERVICE_1_FAQ_Q2', a: 'SERVICE_1_FAQ_A2' },
    ],
  },
  {
    slug: 'drain-cleaning',
    name: 'SERVICE_2_NAME_GOES_HERE',
    keyword: `SERVICE_2_PRIMARY_KEYWORD_GOES_HERE (e.g. drain cleaning ${city})`,
    icon: 'Waves',
    short: 'SERVICE_2_SHORT_DESCRIPTION_GOES_HERE',
    priceFrom: 99,
    duration: 'SERVICE_2_TYPICAL_DURATION_GOES_HERE',
    pricing: 'SERVICE_2_PRICING_EXPLANATION_GOES_HERE',
    hero: 'SERVICE_2_HERO_PARAGRAPH_GOES_HERE',
    includes: [
      'SERVICE_2_INCLUDE_1',
      'SERVICE_2_INCLUDE_2',
      'SERVICE_2_INCLUDE_3',
      'SERVICE_2_INCLUDE_4',
      'SERVICE_2_INCLUDE_5',
    ],
    signs: ['SERVICE_2_SIGN_1','SERVICE_2_SIGN_2','SERVICE_2_SIGN_3','SERVICE_2_SIGN_4','SERVICE_2_SIGN_5'],
    faq: [
      { q: 'SERVICE_2_FAQ_Q1', a: 'SERVICE_2_FAQ_A1' },
      { q: 'SERVICE_2_FAQ_Q2', a: 'SERVICE_2_FAQ_A2' },
    ],
  },
  {
    slug: 'water-heaters',
    name: 'SERVICE_3_NAME_GOES_HERE',
    keyword: `SERVICE_3_PRIMARY_KEYWORD_GOES_HERE (e.g. water heater repair ${city})`,
    icon: 'Flame',
    short: 'SERVICE_3_SHORT_DESCRIPTION_GOES_HERE',
    priceFrom: 1295,
    duration: 'SERVICE_3_TYPICAL_DURATION_GOES_HERE',
    pricing: 'SERVICE_3_PRICING_EXPLANATION_GOES_HERE',
    hero: 'SERVICE_3_HERO_PARAGRAPH_GOES_HERE',
    includes: [
      'SERVICE_3_INCLUDE_1',
      'SERVICE_3_INCLUDE_2',
      'SERVICE_3_INCLUDE_3',
      'SERVICE_3_INCLUDE_4',
      'SERVICE_3_INCLUDE_5',
    ],
    signs: ['SERVICE_3_SIGN_1','SERVICE_3_SIGN_2','SERVICE_3_SIGN_3','SERVICE_3_SIGN_4','SERVICE_3_SIGN_5'],
    faq: [
      { q: 'SERVICE_3_FAQ_Q1', a: 'SERVICE_3_FAQ_A1' },
      { q: 'SERVICE_3_FAQ_Q2', a: 'SERVICE_3_FAQ_A2' },
    ],
  },
  {
    slug: 'leak-detection',
    name: 'SERVICE_4_NAME_GOES_HERE',
    keyword: `SERVICE_4_PRIMARY_KEYWORD_GOES_HERE (e.g. leak detection ${city})`,
    icon: 'Droplets',
    short: 'SERVICE_4_SHORT_DESCRIPTION_GOES_HERE',
    priceFrom: 189,
    duration: 'SERVICE_4_TYPICAL_DURATION_GOES_HERE',
    pricing: 'SERVICE_4_PRICING_EXPLANATION_GOES_HERE',
    hero: 'SERVICE_4_HERO_PARAGRAPH_GOES_HERE',
    includes: [
      'SERVICE_4_INCLUDE_1',
      'SERVICE_4_INCLUDE_2',
      'SERVICE_4_INCLUDE_3',
      'SERVICE_4_INCLUDE_4',
      'SERVICE_4_INCLUDE_5',
    ],
    signs: ['SERVICE_4_SIGN_1','SERVICE_4_SIGN_2','SERVICE_4_SIGN_3','SERVICE_4_SIGN_4','SERVICE_4_SIGN_5'],
    faq: [
      { q: 'SERVICE_4_FAQ_Q1', a: 'SERVICE_4_FAQ_A1' },
      { q: 'SERVICE_4_FAQ_Q2', a: 'SERVICE_4_FAQ_A2' },
    ],
  },
  {
    slug: 'sewer-line',
    name: 'SERVICE_5_NAME_GOES_HERE',
    keyword: `SERVICE_5_PRIMARY_KEYWORD_GOES_HERE (e.g. sewer line repair ${city})`,
    icon: 'Pipette',
    short: 'SERVICE_5_SHORT_DESCRIPTION_GOES_HERE',
    priceFrom: 295,
    duration: 'SERVICE_5_TYPICAL_DURATION_GOES_HERE',
    pricing: 'SERVICE_5_PRICING_EXPLANATION_GOES_HERE',
    hero: 'SERVICE_5_HERO_PARAGRAPH_GOES_HERE',
    includes: [
      'SERVICE_5_INCLUDE_1',
      'SERVICE_5_INCLUDE_2',
      'SERVICE_5_INCLUDE_3',
      'SERVICE_5_INCLUDE_4',
      'SERVICE_5_INCLUDE_5',
    ],
    signs: ['SERVICE_5_SIGN_1','SERVICE_5_SIGN_2','SERVICE_5_SIGN_3','SERVICE_5_SIGN_4','SERVICE_5_SIGN_5'],
    faq: [
      { q: 'SERVICE_5_FAQ_Q1', a: 'SERVICE_5_FAQ_A1' },
      { q: 'SERVICE_5_FAQ_Q2', a: 'SERVICE_5_FAQ_A2' },
    ],
  },
  {
    slug: 'fixtures-faucets',
    name: 'SERVICE_6_NAME_GOES_HERE',
    keyword: `SERVICE_6_PRIMARY_KEYWORD_GOES_HERE`,
    icon: 'Wrench',
    short: 'SERVICE_6_SHORT_DESCRIPTION_GOES_HERE',
    priceFrom: 129,
    duration: 'SERVICE_6_TYPICAL_DURATION_GOES_HERE',
    pricing: 'SERVICE_6_PRICING_EXPLANATION_GOES_HERE',
    hero: 'SERVICE_6_HERO_PARAGRAPH_GOES_HERE',
    includes: [
      'SERVICE_6_INCLUDE_1',
      'SERVICE_6_INCLUDE_2',
      'SERVICE_6_INCLUDE_3',
      'SERVICE_6_INCLUDE_4',
      'SERVICE_6_INCLUDE_5',
    ],
    signs: ['SERVICE_6_SIGN_1','SERVICE_6_SIGN_2','SERVICE_6_SIGN_3','SERVICE_6_SIGN_4','SERVICE_6_SIGN_5'],
    faq: [
      { q: 'SERVICE_6_FAQ_Q1', a: 'SERVICE_6_FAQ_A1' },
      { q: 'SERVICE_6_FAQ_Q2', a: 'SERVICE_6_FAQ_A2' },
    ],
  },
  {
    slug: 'repiping',
    name: 'SERVICE_7_NAME_GOES_HERE',
    keyword: `SERVICE_7_PRIMARY_KEYWORD_GOES_HERE`,
    icon: 'GitFork',
    short: 'SERVICE_7_SHORT_DESCRIPTION_GOES_HERE',
    priceFrom: 4500,
    duration: 'SERVICE_7_TYPICAL_DURATION_GOES_HERE',
    pricing: 'SERVICE_7_PRICING_EXPLANATION_GOES_HERE',
    hero: 'SERVICE_7_HERO_PARAGRAPH_GOES_HERE',
    includes: [
      'SERVICE_7_INCLUDE_1',
      'SERVICE_7_INCLUDE_2',
      'SERVICE_7_INCLUDE_3',
      'SERVICE_7_INCLUDE_4',
      'SERVICE_7_INCLUDE_5',
    ],
    signs: ['SERVICE_7_SIGN_1','SERVICE_7_SIGN_2','SERVICE_7_SIGN_3','SERVICE_7_SIGN_4','SERVICE_7_SIGN_5'],
    faq: [
      { q: 'SERVICE_7_FAQ_Q1', a: 'SERVICE_7_FAQ_A1' },
      { q: 'SERVICE_7_FAQ_Q2', a: 'SERVICE_7_FAQ_A2' },
    ],
  },
  {
    slug: 'commercial',
    name: 'SERVICE_8_NAME_GOES_HERE',
    keyword: `SERVICE_8_PRIMARY_KEYWORD_GOES_HERE`,
    icon: 'Building2',
    short: 'SERVICE_8_SHORT_DESCRIPTION_GOES_HERE',
    priceFrom: 249,
    duration: 'SERVICE_8_TYPICAL_DURATION_GOES_HERE',
    pricing: 'SERVICE_8_PRICING_EXPLANATION_GOES_HERE',
    hero: 'SERVICE_8_HERO_PARAGRAPH_GOES_HERE',
    includes: [
      'SERVICE_8_INCLUDE_1',
      'SERVICE_8_INCLUDE_2',
      'SERVICE_8_INCLUDE_3',
      'SERVICE_8_INCLUDE_4',
      'SERVICE_8_INCLUDE_5',
    ],
    signs: ['SERVICE_8_SIGN_1','SERVICE_8_SIGN_2','SERVICE_8_SIGN_3','SERVICE_8_SIGN_4','SERVICE_8_SIGN_5'],
    faq: [
      { q: 'SERVICE_8_FAQ_Q1', a: 'SERVICE_8_FAQ_A1' },
      { q: 'SERVICE_8_FAQ_Q2', a: 'SERVICE_8_FAQ_A2' },
    ],
  },
];

export const getService = (slug) => services.find((s) => s.slug === slug);
