import { site } from '@/lib/site-config';

const city = site.address.city;

const sharedIncludes = [
  'Arrival window confirmed by phone or text',
  'Clear diagnosis before repair work begins',
  'Up-front options explained in plain language',
  'Respectful cleanup before the technician leaves',
  'Service notes for your records',
];

export const services = [
  {
    slug: 'emergency-plumbing',
    name: '24/7 Emergency Plumbing',
    keyword: `emergency plumber ${city}`,
    icon: 'Siren',
    short: 'Fast help for active leaks, burst pipes, sewer backups, no-water calls, and other urgent plumbing problems.',
    priceFrom: 0,
    duration: 'Immediate dispatch based on urgency and technician availability',
    pricing: 'Emergency pricing is confirmed before approved work begins.',
    hero:
      'When water is moving where it should not be, you need a calm, capable plumber who answers the phone. Maston’s provides emergency plumbing across Tulsa and nearby communities with practical triage, clear next steps, and repair work focused on protecting your home.',
    includes: [
      '24-hour phone response for urgent plumbing issues',
      'Leak isolation and damage-limiting guidance',
      'Burst pipe, sewage backup, and fixture overflow response',
      'Temporary stabilization when a permanent repair needs parts',
      ...sharedIncludes.slice(1),
    ],
    signs: ['Water is actively leaking', 'A pipe has burst', 'Sewage is backing up', 'You have no usable water', 'A fixture will not shut off'],
    faq: [
      { q: 'Should I call if I already shut off the water?', a: 'Yes. Shutting off the water is a smart first step, but a technician can identify the failure, make the repair, and safely restore service.' },
      { q: 'Do emergency calls cover the whole Tulsa metro?', a: `Maston’s handles emergency calls in ${site.serviceArea}. Availability depends on call volume and technician routing.` },
    ],
  },
  {
    slug: 'drain-cleaning',
    name: 'Drain Cleaning',
    keyword: `drain cleaning ${city}`,
    icon: 'Waves',
    short: 'Professional clearing for slow sinks, tubs, showers, kitchen drains, floor drains, and recurring clogs.',
    priceFrom: 0,
    duration: 'Often completed in one visit',
    pricing: 'Your technician confirms the blockage location and recommended method before service.',
    hero:
      'A slow drain is usually a warning, not a random nuisance. Maston’s clears the line, checks for repeat-cause symptoms, and helps you understand whether the issue is isolated or part of a deeper drain system problem.',
    includes: [
      'Sink, shower, tub, kitchen, laundry, and floor drain clearing',
      'Cable or machine cleaning selected for the line',
      'Assessment of repeat-clog patterns',
      'Recommendations to prevent avoidable backups',
      ...sharedIncludes,
    ],
    signs: ['Water drains slowly', 'Several fixtures gurgle', 'A drain smells sour', 'Clogs return after store-bought cleaner', 'Water backs up into another fixture'],
    faq: [
      { q: 'Can you clear kitchen grease clogs?', a: 'Yes. Maston’s clears kitchen lines and can recommend next steps if grease buildup is severe or recurring.' },
      { q: 'Do you inspect sewer lines too?', a: 'If symptoms suggest a main-line issue, the technician can recommend sewer inspection or hydro jetting instead of treating it as a simple fixture clog.' },
    ],
  },
  {
    slug: 'sewer-drain',
    name: 'Sewer and Drain Service',
    keyword: `sewer and drain service ${city}`,
    icon: 'Pipette',
    short: 'Main-line clogs, sewer backups, camera inspections, sewer repair planning, and root-intrusion troubleshooting.',
    priceFrom: 0,
    duration: 'Inspection and clearing often same day; repairs scheduled by scope',
    pricing: 'Inspection findings determine whether cleaning, repair, or replacement is the right path.',
    hero:
      'Sewer problems can turn stressful quickly. Maston’s focuses on the full picture: where the blockage is, why it happened, and whether cleaning alone is enough to protect the home from another backup.',
    includes: [
      'Main sewer line diagnosis',
      'Sewer camera inspection when appropriate',
      'Root intrusion and collapsed-line assessment',
      'Repair and replacement recommendations',
      ...sharedIncludes,
    ],
    signs: ['Multiple drains are backing up', 'Toilets bubble when fixtures drain', 'Sewage odor is present', 'Yard spots stay unusually wet', 'Backups return after cleaning'],
    faq: [
      { q: 'Do all sewer problems require replacement?', a: 'No. Some lines need cleaning or sectional repair. Replacement is recommended only when the condition of the line makes it the practical long-term fix.' },
      { q: 'Can you help with root intrusion?', a: 'Yes. Maston’s can clear root-related blockages and explain repair options when roots have damaged the pipe.' },
    ],
  },
  {
    slug: 'water-heaters',
    name: 'Water Heater Repair and Installation',
    keyword: `water heater repair ${city}`,
    icon: 'Flame',
    short: 'Repair, replacement, maintenance, and installation for tank and tankless water heaters.',
    priceFrom: 0,
    duration: 'Many repairs same day; replacements scheduled by equipment fit',
    pricing: 'Repair versus replacement options are reviewed before work begins.',
    hero:
      'Hot water should be reliable, efficient, and sized for the way your household actually lives. Maston’s diagnoses water heater failures, installs replacement equipment, and helps Tulsa homeowners choose between tank and tankless solutions.',
    includes: [
      'No-hot-water diagnosis',
      'Tank and tankless installation options',
      'Expansion tank, valve, and connection review',
      'Age and efficiency guidance',
      ...sharedIncludes,
    ],
    signs: ['Water turns cold quickly', 'The tank is leaking', 'Hot water smells metallic', 'The pilot will not stay lit', 'The unit is noisy or rusty'],
    faq: [
      { q: 'Do you install tankless water heaters?', a: 'Yes. Maston’s installs and services tankless systems and can explain gas, venting, and household-demand considerations.' },
      { q: 'Should I repair or replace my water heater?', a: 'That depends on age, tank condition, failure type, and repair cost. The technician will explain both paths clearly.' },
    ],
  },
  {
    slug: 'leak-detection',
    name: 'Leak Detection and Repair',
    keyword: `leak detection ${city}`,
    icon: 'Droplets',
    short: 'Targeted leak diagnosis for hidden pipe leaks, slab symptoms, fixture leaks, and unexplained water use.',
    priceFrom: 0,
    duration: 'Diagnosis timing depends on access and symptoms',
    pricing: 'Repair options are quoted after the leak source is identified.',
    hero:
      'Hidden leaks rarely fix themselves. Maston’s tracks symptoms carefully, narrows the source, and recommends a repair that protects the home without unnecessary demolition.',
    includes: [
      'Visible and hidden leak assessment',
      'Fixture, supply, drain, and slab symptom review',
      'Water meter and pressure clues',
      'Repair recommendations matched to access and damage risk',
      ...sharedIncludes,
    ],
    signs: ['The water bill jumped', 'You hear running water', 'Floors feel warm or damp', 'Paint bubbles or drywall stains appear', 'Moldy smells persist'],
    faq: [
      { q: 'Can you find leaks behind walls?', a: 'Maston’s uses symptom tracing and appropriate diagnostic methods to narrow the source before recommending access or repair work.' },
      { q: 'Is a slab leak an emergency?', a: 'It can be. If you suspect a slab leak, call promptly so the issue can be evaluated before damage spreads.' },
    ],
  },
  {
    slug: 'gas-lines',
    name: 'Gas Line Services',
    keyword: `gas line plumber ${city}`,
    icon: 'Flame',
    short: 'Gas line repair, replacement, appliance hookups, and safety-focused diagnosis by qualified plumbing professionals.',
    priceFrom: 0,
    duration: 'Varies by inspection, access, and permitting needs',
    pricing: 'Gas work is scoped carefully and quoted before installation or repair.',
    hero:
      'Gas line work demands precision and respect for safety. Maston’s helps with gas piping repairs, appliance connections, and replacement planning for Tulsa-area homes and businesses.',
    includes: [
      'Gas leak concern evaluation',
      'Gas appliance connection support',
      'Line repair and replacement planning',
      'Code-aware installation practices',
      ...sharedIncludes,
    ],
    signs: ['You smell gas', 'A gas appliance needs connection', 'A line is corroded or damaged', 'A remodel needs gas rerouting', 'A utility or inspector flagged the line'],
    faq: [
      { q: 'What should I do if I smell gas?', a: 'Leave the area, avoid switches or flames, call the gas utility or emergency services, then contact a qualified professional after the immediate hazard is addressed.' },
      { q: 'Can you hook up gas appliances?', a: 'Yes. Maston’s can help with appropriate gas appliance connections and related line work.' },
    ],
  },
  {
    slug: 'water-filtration',
    name: 'Water Filtration and Softening',
    keyword: `water filtration ${city}`,
    icon: 'Droplets',
    short: 'Cleaner, better-feeling water through filtration, softening, and whole-home water quality solutions.',
    priceFrom: 0,
    duration: 'Consultation and installation timing depends on system type',
    pricing: 'System recommendations are based on water goals, home layout, and maintenance expectations.',
    hero:
      'Tulsa-area water can leave homeowners dealing with taste, scale, residue, and appliance wear. Maston’s helps match the right filtration or softening approach to your home instead of selling a one-size-fits-all box.',
    includes: [
      'Whole-home filtration consultation',
      'Water softener installation planning',
      'Point-of-use filtration options',
      'Maintenance and replacement guidance',
      ...sharedIncludes,
    ],
    signs: ['Water tastes or smells off', 'Fixtures collect white scale', 'Skin or hair feels dry after showers', 'Appliances show mineral buildup', 'You want better drinking water'],
    faq: [
      { q: 'Do I need filtration, softening, or both?', a: 'The answer depends on your water concerns. Maston’s can explain the difference and recommend the right approach for your home.' },
      { q: 'Can filtration protect appliances?', a: 'The right system can reduce scale and sediment that contribute to appliance wear.' },
    ],
  },
  {
    slug: 'fixtures-toilets-disposals',
    name: 'Fixtures, Toilets, and Disposals',
    keyword: `toilet faucet garbage disposal repair ${city}`,
    icon: 'Wrench',
    short: 'Repair and installation for toilets, faucets, sinks, showers, tubs, garbage disposals, and everyday fixtures.',
    priceFrom: 0,
    duration: 'Many fixture repairs completed in one visit',
    pricing: 'Pricing depends on fixture type, parts, access, and whether repair or replacement is best.',
    hero:
      'Small fixture problems can waste water, damage cabinets, and make daily routines frustrating. Maston’s repairs and replaces the parts of your plumbing system you touch every day.',
    includes: [
      'Toilet repair and replacement',
      'Faucet, sink, shower, and tub repair',
      'Garbage disposal service and installation',
      'Fixture upgrade support during remodels',
      ...sharedIncludes,
    ],
    signs: ['A toilet runs constantly', 'A faucet drips', 'A disposal hums or jams', 'A shower valve is hard to control', 'A fixture is outdated or leaking'],
    faq: [
      { q: 'Can you install owner-supplied fixtures?', a: 'In many cases, yes. The technician can confirm compatibility and explain any warranty limitations before installation.' },
      { q: 'Do you repair garbage disposals?', a: 'Yes. Maston’s can diagnose jams, leaks, motor failure, and installation issues.' },
    ],
  },
  {
    slug: 'repiping',
    name: 'Repiping and Pipe Repair',
    keyword: `repiping plumber ${city}`,
    icon: 'GitFork',
    short: 'Pipe repair, partial repiping, whole-home repiping, and water line replacement for aging or damaged systems.',
    priceFrom: 0,
    duration: 'Project timeline depends on home size and scope',
    pricing: 'Repiping is quoted after a site review and scope discussion.',
    hero:
      'When repairs keep stacking up, the smarter solution may be targeted pipe replacement or a larger repipe. Maston’s helps homeowners understand the tradeoffs, materials, timeline, and disruption before committing.',
    includes: [
      'Copper, PEX, and supply-line assessment',
      'Partial and whole-home repipe planning',
      'Pressure and corrosion symptom review',
      'Water line repair and replacement options',
      ...sharedIncludes,
    ],
    signs: ['Leaks keep appearing', 'Water pressure drops throughout the home', 'Water looks rusty', 'Pipes are old or corroded', 'A remodel exposes failing pipework'],
    faq: [
      { q: 'How do I know if I need repiping?', a: 'Repeated leaks, widespread corrosion, and whole-home pressure problems are common signs. A site review confirms whether repair or repiping makes more sense.' },
      { q: 'Can repiping be done in phases?', a: 'Often, yes. Maston’s can discuss priority areas and practical phasing based on the condition of the system.' },
    ],
  },
  {
    slug: 'commercial-plumbing',
    name: 'Commercial Plumbing',
    keyword: `commercial plumber ${city}`,
    icon: 'Building2',
    short: 'Responsive plumbing and drain support for offices, restaurants, retail spaces, property managers, and local facilities.',
    priceFrom: 0,
    duration: 'Scheduled around business priority and access',
    pricing: 'Commercial work is scoped by urgency, access, fixtures, and operating needs.',
    hero:
      'A plumbing problem at work can interrupt customers, staff, and revenue. Maston’s supports Tulsa-area businesses with practical scheduling, clear communication, and service designed to keep operations moving.',
    includes: [
      'Commercial drain and fixture service',
      'Water heater and backflow support',
      'Restroom plumbing repairs',
      'Preventive service agreement planning',
      ...sharedIncludes,
    ],
    signs: ['A restroom is out of service', 'Drains slow during peak hours', 'A water heater cannot keep up', 'A property needs reliable vendor support', 'A recurring issue needs documentation'],
    faq: [
      { q: 'Do you work with property managers?', a: 'Yes. Maston’s can coordinate with owners, managers, tenants, and on-site contacts to resolve plumbing issues efficiently.' },
      { q: 'Can you help prevent repeat business interruptions?', a: 'Yes. Preventive service agreements can be used to schedule routine checks and drain maintenance where appropriate.' },
    ],
  },
  {
    slug: 'service-agreements',
    name: 'Service Agreements',
    keyword: `plumbing service agreement ${city}`,
    icon: 'ShieldCheck',
    short: 'Preventive plumbing maintenance plans for homeowners and businesses that prefer fewer surprises.',
    priceFrom: 0,
    duration: 'Scheduled maintenance visits by agreement',
    pricing: 'Plans are tailored to the property type, system needs, and service frequency.',
    hero:
      'The best plumbing emergencies are the ones you never have. Maston’s service agreements help homeowners and businesses keep an eye on aging parts, water heaters, drains, and risk points before they become urgent.',
    includes: [
      'Scheduled plumbing maintenance',
      'Water heater and fixture checks',
      'Drain and sewer risk review',
      'Priority planning for known issues',
      ...sharedIncludes,
    ],
    signs: ['You manage multiple properties', 'Your home has aging plumbing', 'You have had repeat drain issues', 'Downtime would be costly', 'You prefer planned maintenance'],
    faq: [
      { q: 'Are service agreements only for businesses?', a: 'No. They can be useful for homeowners, rental properties, and commercial spaces.' },
      { q: 'Can the plan be customized?', a: 'Yes. Maston’s can align the agreement with your property, plumbing history, and maintenance goals.' },
    ],
  },
];

export const getService = (slug) => services.find((s) => s.slug === slug);
